// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLoXchdNrTKi_pTeXqJK_QmF8PnQM2phY',
    appId: '1:884607307332:web:0cdb494e5025ebb0a5f611',
    messagingSenderId: '884607307332',
    projectId: 'loginsignup-54db5',
    authDomain: 'loginsignup-54db5.firebaseapp.com',
    storageBucket: 'loginsignup-54db5.firebasestorage.app',
    measurementId: 'G-F7NHCRJKBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaiyPHxVxSuRaJmn3T8VcQOI9BAZbknac',
    appId: '1:884607307332:android:195184b57d2aeff3a5f611',
    messagingSenderId: '884607307332',
    projectId: 'loginsignup-54db5',
    storageBucket: 'loginsignup-54db5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeOJd5CFxBSEhhKPy0PtUQvbGUMjU51mk',
    appId: '1:884607307332:ios:fd1671f54cbc84d8a5f611',
    messagingSenderId: '884607307332',
    projectId: 'loginsignup-54db5',
    storageBucket: 'loginsignup-54db5.firebasestorage.app',
    iosBundleId: 'com.example.nexelloginrgistration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeOJd5CFxBSEhhKPy0PtUQvbGUMjU51mk',
    appId: '1:884607307332:ios:fd1671f54cbc84d8a5f611',
    messagingSenderId: '884607307332',
    projectId: 'loginsignup-54db5',
    storageBucket: 'loginsignup-54db5.firebasestorage.app',
    iosBundleId: 'com.example.nexelloginrgistration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLoXchdNrTKi_pTeXqJK_QmF8PnQM2phY',
    appId: '1:884607307332:web:7af5057510795706a5f611',
    messagingSenderId: '884607307332',
    projectId: 'loginsignup-54db5',
    authDomain: 'loginsignup-54db5.firebaseapp.com',
    storageBucket: 'loginsignup-54db5.firebasestorage.app',
    measurementId: 'G-BGZVC7SC36',
  );
}
